# automatically generated by the FlatBuffers compiler, do not modify

# namespace: WebProtocol

import flatbuffers

class BuildingConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBuildingConfig(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BuildingConfig()
        x.Init(buf, n + offset)
        return x

    # BuildingConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BuildingConfig
    def DesiredTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BuildingConfig
    def SafetyRange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BuildingConfigStart(builder): builder.StartObject(2)
def BuildingConfigAddDesiredTemp(builder, desiredTemp): builder.PrependFloat32Slot(0, desiredTemp, 0.0)
def BuildingConfigAddSafetyRange(builder, safetyRange): builder.PrependFloat32Slot(1, safetyRange, 0.0)
def BuildingConfigEnd(builder): return builder.EndObject()
